name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Invoke MSBuild
      run: cibuild.bat
    - uses: actions/upload-artifact@master
      with:
        name: Artifacts
        path: bin/Release
